### ISSUE TITLE
Fix visual style of code highlighting

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/gohugoioTheme#50] opened 2017-07-19 05:00 UTC
From https://github.com/gohugoio/hugoDocs/issues/45

> * I'm not a big fan of the colour scheme used (too much bright pink)
> * A bigger problem is the big variations of how it looks; some Go templates are blue, some are black ... Some have white background, some grey. It is a Christmas tree.
> * Not sure what "```golang" is supposed to trigger -- Go is the name of the language, and what is mostly posted are Go template code and not Go code. Currently maybe html would be a better choice, or if someone could create an improved "Go template highlighter rules" based on HTML (look at the Atom editor, which looks great with Hugo).

@budparr I will change these all to `html` if we want to extend the corresponding hljs module and you think that's the best approach.

**Comment by budparr** [comment] 2017-07-19 13:45
At one point I tried individually styling the Hugo specific templating but that didn't work, though perhaps it was due to all the different styles.  I guess the problem is consistency, so I suppose HTML is fine. But I think you understand this better than I, to be honest.

**Comment by budparr** [comment] 2017-07-19 14:32
@rdwatters I think this issue should be closed in favor of the one in HugoDocs since the change really is in content. The design issue (changing the color scheme) belongs here. Agree?

**Comment by moorereason** [comment] 2017-07-19 15:48
I'm sure I'm in the minority, but I prefer very minimal syntax highlighting.  I use https://github.com/robertmeta/nofrils when programming in vim to highlight only comments and strings.

Syntax highlighting in HTML bloats the page markup IMHO.  There's probably a 2% chance you guys will agree with me, but I wanted to share a different perspective anyway.

**Comment by budparr** [comment] 2017-07-19 15:51
🙌 I agree with you, @moorereason. I only implemented in the first place to go with the flow, to be honest.

**Comment by rdwatters** [comment] 2017-07-19 18:58
Sure thing @budparr I guess we will invariable have some crossover between repos/issues while everything is somewhat new:)

I'll make all the code blocks golang and leave it to you, @bep, and @moorereason to make it look awesome.

**Comment by bep** [comment] 2017-07-19 19:02
This issue isn't as much about the beauty of code highlighting as the consistency of the site. @budparr what you implemented does not work, which is why we're having this issue.

**Comment by budparr** [comment] 2017-07-19 19:15
Very well. This was my first time doing code-highlighting, so in retrospect I should have had some review. I'm happy to take another crack at it if you prefer.

**Comment by budparr** [comment] 2017-07-19 19:19
This is the source of my mistake, I believe: I was under the impression that the cause of the issue was content, like this, below, where some code is wrapped in backticks and some wrapped in Hugo `code` shortode. 

```
### Example: List All Site Tags

```html
<ul id="all-tags">
  {{ range $name, $taxonomy := .Site.Taxonomies.tags }}
    <li><a href="{{ "/tags/" | relLangURL }}{{ $name | urlize }}">{{ $name }}</a></li>
  {{ end }}
</ul>
```

### Example: List All Taxonomies, Terms, and Assigned Content

This example will list all taxonomies and their terms, as well as all the content assigned to each of the terms.

{{% code file="layouts/partials/all-taxonomies.html" download="all-taxonomies.html" download="all-taxonomies.html" %}}
```html
<section>
  <ul id="all-taxonomies">
    {{ range $taxonomyname, $taxonomy := .Site.Taxonomies }}
      <li><a href="{{ "/" | relLangURL}}{{ $taxonomyname | urlize }}">{{ $taxonomyname }}</a>
        <ul>
          {{ range $key, $value := $taxonomy }}
          <li> {{ $key }} </li>
                <ul>
                {{ range $value.Pages }}
                    <li hugo-nav="{{ .RelPermalink}}"><a href="{{ .Permalink}}"> {{ .LinkTitle }} </a> </li>
                {{ end }}
                </ul>
          {{ end }}
        </ul>
      </li>
    {{ end }}
  </ul>
</section>
```
{{% /code %}}
```

**Closed** 2017-07-19 19:31 UTC
Labels: bug

**Comment by budparr** [comment] 2017-07-19 19:45
At the risk of sounding antagonistic, the issue I thought you were referring to (see above) still exists:

<img width="702" alt="screen shot 2017-07-19 at 3 41 12 pm" src="https://user-images.githubusercontent.com/115347/28386218-d886996e-6c98-11e7-9d6a-d9b2d98a07bf.png">
https://github.com/gohugoio/hugoDocs/blob/master/content/templates/taxonomy-templates.md

And, I agree that no highlight is better than inconsistent highlight (also see my comment above), but it would be nice to differentiate the Hugo code from the HTML here.

 I've lobbied before to keep the HTML to absolute minimum in these examples (in the concept repo), which is one way to do, or, come up with our own highlights, which I'm happy to do at some point, if you feel like it's a suitable option.

**Comment by bep** [comment] 2017-07-19 19:53
>At the risk of sounding antagonistic, the issue I thought you were referring to (see above) still exists:

That was not the issue I was talking about, but feel free to fix any other issue you may have.
